# Generated by Django 2.1.3 on 2018-12-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=80, unique=True)),
                ('jabatan', models.CharField(blank=True, max_length=20, null=True)),
                ('seksi', models.CharField(blank=True, max_length=20, null=True)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('photo_url', models.CharField(max_length=80, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
