# Generated by Django 2.1.3 on 2018-12-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datasource',
            fields=[
                ('uuid', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=80)),
                ('deskripsi', models.CharField(max_length=255)),
                ('seksi', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
        ),
    ]
