# Generated by Django 2.1.3 on 2018-12-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataMikro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('uuid', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=80)),
                ('deskripsi', models.CharField(max_length=255)),
                ('seksi', models.CharField(max_length=20)),
                ('uuid_datasource', models.CharField(max_length=80)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
        ),
    ]
