# Generated by Django 2.1.3 on 2018-12-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataMikro', '0002_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='uuid_user',
            field=models.CharField(default='0', max_length=80),
        ),
    ]
