# Generated by Django 2.1.3 on 2018-12-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='publikasi',
            fields=[
                ('uuid', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=80)),
                ('deskripsi', models.CharField(default='None', max_length=300, null=True)),
                ('isi', models.TextField(null=True)),
                ('seksi', models.CharField(max_length=20)),
                ('tag', models.TextField(null=True)),
                ('tanggal_terbit', models.DateTimeField()),
                ('type_pub', models.CharField(default='pdf', max_length=80)),
                ('data_tahun', models.CharField(default='2018', max_length=4)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
        ),
    ]
