# Generated by Django 2.1.3 on 2018-12-09 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aplikasi',
            fields=[
                ('uuid', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('versi', models.CharField(max_length=10)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='basis_data',
            fields=[
                ('uuid', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('versi', models.CharField(max_length=10)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='kegiatan',
            fields=[
                ('uuid', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('nama_aplikasi', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='basis_data',
            name='uuid_kegiatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Versioning.kegiatan'),
        ),
        migrations.AddField(
            model_name='aplikasi',
            name='uuid_kegiatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Versioning.kegiatan'),
        ),
    ]
